# Generated by Django 3.2.12 on 2022-02-28 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('whyness_django', '0025_alter_audio_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='MBTI',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('IE', models.CharField(default='', max_length=1)),
                ('NS', models.CharField(default='', max_length=1)),
                ('TF', models.CharField(default='', max_length=1)),
                ('PJ', models.CharField(default='', max_length=1)),
                ('update_ip', models.GenericIPAddressField(default='::1')),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='whyness_django.authuser')),
            ],
        ),
    ]
