# Generated by Django 3.2.12 on 2022-03-23 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('whyness_django', '0026_alter_audio_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('hostip', models.GenericIPAddressField(null=True)),
                ('errorcode', models.TextField(blank=True, verbose_name='Error code')),
                ('errormessage', models.TextField(blank=True, verbose_name='Error message')),
                ('useragent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='whyness_django.useragent')),
            ],
        ),
    ]
