version: "3.7"

services:
  web:
    build: .
    command: python manage.py runserver IP.REMOVED:8000
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

