# Generated by Django 3.2.11 on 2022-02-16 19:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=100)),
                ('email', models.EmailField(blank=True, max_length=150)),
                ('xref', models.UUIDField(default=uuid.uuid4, verbose_name='Contact Reference')),
                ('status', models.SmallIntegerField(default=1)),
                ('is_prospect', models.BooleanField(default=False)),
                ('is_registered', models.BooleanField(default=False)),
                ('use_whatsapp', models.BooleanField(default=False)),
                ('use_email', models.BooleanField(default=False)),
                ('update_ip', models.GenericIPAddressField(default='::1')),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='', max_length=100)),
                ('slug', models.CharField(default='', max_length=100, unique=True)),
                ('status', models.SmallIntegerField(default=1)),
                ('is_whatsapp', models.BooleanField(default=False)),
                ('is_email', models.BooleanField(default=False)),
                ('update_ip', models.GenericIPAddressField(default='::1')),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('message_html', models.TextField(blank=True)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ContactRecord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.SmallIntegerField(default=1)),
                ('message_status', models.SmallIntegerField(default=1)),
                ('sent_date', models.DateTimeField(auto_now_add=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='whyness_crm.contact')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='whyness_crm.message')),
            ],
        ),
    ]
