# Generated by Django 3.2.12 on 2022-02-21 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('whyness_django', '0022_tracker_trackeritem'),
        ('whyness_crm', '0003_auto_20220221_0934'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersql',
            name='contact_type',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='AuthUserContactRecord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.SmallIntegerField(default=1)),
                ('message_status', models.SmallIntegerField(default=1)),
                ('sent_date', models.DateTimeField(auto_now_add=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='whyness_django.authuser')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='whyness_crm.message')),
            ],
        ),
    ]
