# Generated by Django 3.2.12 on 2022-02-22 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whyness_crm', '0004_auto_20220221_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
