# Generated by Django 3.2.12 on 2022-02-22 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whyness_crm', '0005_message_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='academic_institution',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='contact',
            name='actively_seeking',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='contact',
            name='age_range',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='contact',
            name='commit_hours',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='contact',
            name='country',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='contact',
            name='employment_status',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='contact',
            name='fulfilled',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='contact',
            name='fulfiment_importance',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='contact',
            name='how_did_you_hear',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='contact',
            name='how_long',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='contact',
            name='key_factors',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='contact',
            name='mobile',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='contact',
            name='release_date',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='contact',
            name='years_experience',
            field=models.CharField(default='', max_length=20),
        ),
    ]
