# Generated by Django 3.2.12 on 2022-02-23 17:27

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('whyness_django', '0024_authuser_xref'),
        ('whyness_crm', '0006_auto_20220222_2044'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackerDestination',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.CharField(default='', max_length=500)),
                ('xref', models.UUIDField(default=uuid.uuid4, verbose_name='Tracker Destination')),
            ],
        ),
        migrations.CreateModel(
            name='ContactTrackerClick',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('update_ip', models.GenericIPAddressField(default='::1')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='whyness_crm.contact')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='whyness_crm.trackerdestination')),
            ],
        ),
        migrations.CreateModel(
            name='AuthUserTrackerClick',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('update_ip', models.GenericIPAddressField(default='::1')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='whyness_django.authuser')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='whyness_crm.trackerdestination')),
            ],
        ),
    ]
