# Generated by Django 3.2.12 on 2022-02-25 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whyness_crm', '0007_authusertrackerclick_contacttrackerclick_trackerdestination'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersql',
            name='sql_once',
            field=models.BooleanField(default=True),
        ),
    ]
