# Generated by Django 3.2.12 on 2022-02-28 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whyness_crm', '0008_usersql_sql_once'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackerdestination',
            name='status',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='trackerdestination',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
    ]
