# Generated by Django 3.2.12 on 2022-03-16 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whyness_crm', '0011_remove_usersql_sql_once'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='academic_institution',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='actively_seeking',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='age_range',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='commit_hours',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='country',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='employment_status',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='fulfilled',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='fulfiment_importance',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='how_did_you_hear',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='how_long',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='key_factors',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='mobile',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='release_date',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='years_experience',
        ),
        migrations.AddField(
            model_name='contact',
            name='release',
            field=models.SmallIntegerField(default=1),
        ),
    ]
