# Generated by Django 3.2.15 on 2022-09-27 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whyness_crm', '0012_auto_20220316_1431'),
    ]

    sql_create_contact = """
    CREATE VIEW whyness_crm_contact_view AS
    SELECT
        record.id,
        contact.name,
        contact.email,
        contact.xref AS contact_xref,
        contact.status,
        record.sent_date,
        message.title AS message_title,
        message.description AS message_description
    FROM whyness_crm_contactrecord AS record
    INNER JOIN whyness_crm_contact AS contact
    ON contact.id = record.contact_id
    INNER JOIN whyness_crm_message AS message
    ON message.id = record.message_id
    """

    sql_create_user = """
    CREATE VIEW whyness_crm_user_view AS
    SELECT
        record.id,
        authuser.name,
        authuser.email,
        authuser.xref AS user_xref,
        authuser.status,
        record.sent_date,
        message.title AS message_title,
        message.description AS message_description
    FROM whyness_crm_authusercontactrecord AS record
    INNER JOIN whyness_django_authuser AS authuser
    ON authuser.id = record.contact_id
    INNER JOIN whyness_crm_message AS message
    ON message.id = record.message_id
    """
    sql_create_contact_tracker = """
    CREATE VIEW whyness_crm_contact_tracker_view AS
    SELECT
        record.id,
        contact.name,
        contact.email,
        contact.xref AS contact_xref,
        contact.status,
        contact.create_date,
        record.sent_date,
        message.title,
        message.description
    FROM whyness_crm_contactrecord AS record
    INNER JOIN whyness_crm_contact AS contact
    ON contact.id = record.contact_id
    INNER JOIN whyness_crm_message AS message
    ON message.id = record.message_id
    """
    sql_create_user_tracker = """
    CREATE VIEW whyness_crm_user_tracker_view AS
    SELECT
        record.id,
        contact.name,
        contact.email,
        contact.xref AS contact_xref,
        contact.status,
        contact.create_date,
        record.sent_date,
        message.title,
        message.description
    FROM whyness_crm_contactrecord AS record
    INNER JOIN whyness_django_authuser AS contact
    ON contact.id = record.contact_id
    INNER JOIN whyness_crm_message AS message
    ON message.id = record.message_id
    """

    sql_drop_contact = "DROP VIEW whyness_crm_contact_view"
    sql_drop_user = "DROP VIEW whyness_crm_user_view"
    sql_drop_contact_tracker = "DROP VIEW whyness_crm_contact_tracker_view"
    sql_drop_user_tracker = "DROP VIEW whyness_crm_user_tracker_view"

    operations = [
        migrations.RunSQL(
            sql=[
                sql_create_contact,
                sql_create_user,
                sql_create_contact_tracker,
                sql_create_user_tracker,
            ],
            reverse_sql=[
                sql_drop_contact,
                sql_drop_user,
                sql_drop_contact_tracker,
                sql_drop_user_tracker,
            ],
        )
    ]
