# Generated by Django 3.2.16 on 2022-10-17 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('whyness_crm', '0013_tracker_view'),
    ]

    sql_add_contact_status = """
    INSERT INTO whyness_crm_contactstatus (
        title,
        description,
        status,
        create_date,
        update_date
    )
    VALUES ('Prospect', 'Prospect', 1, now(), now());
    INSERT INTO whyness_crm_contactstatus (
        title,
        description,
        status,
        create_date,
        update_date
    )
    VALUES ('Waitlist (Registered)', 'Waitlist (Registered)', 1, now(), now());
    INSERT INTO whyness_crm_contactstatus (
        title,
        description,
        status,
        create_date,
        update_date
    )
    VALUES ('Onboarded', 'Onboarded', 1, now(), now());
    INSERT INTO whyness_crm_contactstatus (
        title,
        description,
        status,
        create_date,
        update_date
    )
    VALUES ('Activated', 'Activated', 1, now(), now());
    INSERT INTO whyness_crm_contactstatus (
        title,
        description,
        status,
        create_date,
        update_date
    )
    VALUES ('Engaged', 'Engaged', 1, now(), now());
    INSERT INTO whyness_crm_contactstatus (
        title,
        description,
        status,
        create_date,
        update_date
    )
    VALUES ('Engaged Advanced', 'Engaged Advanced', 1, now(), now());
    INSERT INTO whyness_crm_contactstatus (
        title,
        description,
        status,
        create_date,
        update_date
    )
    VALUES ('Lapsed/Churned', 'Lapsed/Churned', 1, now(), now());
    INSERT INTO whyness_crm_contactstatus (
        title,
        description,
        status,
        create_date,
        update_date
    )
    VALUES ('Completed', 'Completed', 1, now(), now());
    """

    sql_create_contact_view = """
    CREATE OR REPLACE VIEW whyness_crm_contact_view AS
    SELECT
        record.id,
        contact.name,
        contact.email,
        contact.xref AS contact_xref,
        contact.status_id,
        status.title AS status_title,
        record.sent_date,
        message.title AS message_title,
        message.description AS message_description
    FROM whyness_crm_contactrecord AS record
    INNER JOIN whyness_crm_contact AS contact
    ON contact.id = record.contact_id
    INNER JOIN whyness_crm_contactstatus AS status
    ON status.id = record.status
    INNER JOIN whyness_crm_message AS message
    ON message.id = record.message_id
    """

    sql_create_contact_tracker_view = """
    CREATE OR REPLACE VIEW whyness_crm_contact_tracker_view AS
    SELECT
        record.id,
        contact.name,
        contact.email,
        contact.xref AS contact_xref,
        contact.status_id,
        status.title AS status_title,
        contact.create_date,
        record.sent_date,
        message.title,
        message.description
    FROM whyness_crm_contactrecord AS record
    INNER JOIN whyness_crm_contact AS contact
    ON contact.id = record.contact_id
    INNER JOIN whyness_crm_contactstatus AS status
    ON status.id = record.status
    INNER JOIN whyness_crm_message AS message
    ON message.id = record.message_id
    """

    sql_revert_contact_view = """
    CREATE OR REPLACE VIEW whyness_crm_contact_view AS
    SELECT
        record.id,
        contact.name,
        contact.email,
        contact.xref AS contact_xref,
        contact.status,
        record.sent_date,
        message.title AS message_title,
        message.description AS message_description
    FROM whyness_crm_contactrecord AS record
    INNER JOIN whyness_crm_contact AS contact
    ON contact.id = record.contact_id
    INNER JOIN whyness_crm_message AS message
    ON message.id = record.message_id
    """

    sql_revert_contact_tracker_view = """
    CREATE OR REPLACE VIEW whyness_crm_contact_tracker_view AS
    SELECT
        record.id,
        contact.name,
        contact.email,
        contact.xref AS contact_xref,
        contact.status,
        contact.create_date,
        record.sent_date,
        message.title,
        message.description
    FROM whyness_crm_contactrecord AS record
    INNER JOIN whyness_crm_contact AS contact
    ON contact.id = record.contact_id
    INNER JOIN whyness_crm_message AS message
    ON message.id = record.message_id
    """

    sql_drop_contact_view = "DROP VIEW IF EXISTS whyness_crm_contact_view"
    sql_drop_contact_tracker_view = "DROP VIEW IF EXISTS whyness_crm_contact_tracker_view"

    operations = [
        migrations.RunSQL(
            sql=[
                sql_drop_contact_view,
                sql_drop_contact_tracker_view,
            ],
            reverse_sql=[
                sql_revert_contact_view,
                sql_revert_contact_tracker_view,
            ],
        ),
        migrations.CreateModel(
            name='ContactStatus',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='', max_length=100)),
                ('description', models.TextField(default='')),
                ('status', models.SmallIntegerField(default=1)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RunSQL(
            sql=[
                sql_add_contact_status,
            ],
            reverse_sql=[],
        ),
        migrations.AlterField(
            model_name='contact',
            name='status',
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to='whyness_crm.contactstatus'
            ),
        ),
        migrations.RunSQL(
            sql=[
                sql_create_contact_view,
                sql_create_contact_tracker_view,
            ],
            reverse_sql=[
                sql_drop_contact_view,
                sql_drop_contact_tracker_view,
            ],
        ),
    ]
