# Generated by Django 3.2.12 on 2022-03-09 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('whyness_django', '0026_alter_audio_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='SweetSpotConfidence',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='', max_length=100)),
                ('status', models.SmallIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='SweetSpotImpact',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='', max_length=100)),
                ('status', models.SmallIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='SweetSpotStrength',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='', max_length=100)),
                ('status', models.SmallIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='SweetSpotValue',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='', max_length=100)),
                ('status', models.SmallIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='SweetSpot',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ip', models.GenericIPAddressField(default='::1')),
                ('valueother', models.CharField(default='', max_length=100)),
                ('strengthother', models.CharField(default='', max_length=100)),
                ('impactother', models.CharField(default='', max_length=100)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('impact1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='whyness_userfeedback.sweetspotimpact')),
                ('impact2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='whyness_userfeedback.sweetspotimpact')),
                ('impact3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='whyness_userfeedback.sweetspotimpact')),
                ('impactconfidence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='whyness_userfeedback.sweetspotconfidence')),
                ('strength1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='whyness_userfeedback.sweetspotstrength')),
                ('strength2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='whyness_userfeedback.sweetspotstrength')),
                ('strength3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='whyness_userfeedback.sweetspotstrength')),
                ('strengthconfidence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='whyness_userfeedback.sweetspotconfidence')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='whyness_django.authuser')),
                ('useragent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='whyness_django.useragent')),
                ('value1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='whyness_userfeedback.sweetspotvalue')),
                ('value2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='whyness_userfeedback.sweetspotvalue')),
                ('value3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='whyness_userfeedback.sweetspotvalue')),
                ('valueconfidence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='whyness_userfeedback.sweetspotconfidence')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
