# Generated by Django 3.2.12 on 2022-03-09 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whyness_userfeedback', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sweetspotconfidence',
            name='sort_order',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sweetspotimpact',
            name='sort_order',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sweetspotstrength',
            name='sort_order',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sweetspotvalue',
            name='sort_order',
            field=models.SmallIntegerField(default=0),
        ),
    ]
