# Generated by Django 3.2.12 on 2022-03-09 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whyness_userfeedback', '0003_auto_20220309_1541'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sweetspotconfidence',
            options={'ordering': ['sort_order', 'title']},
        ),
        migrations.AlterModelOptions(
            name='sweetspotimpact',
            options={'ordering': ['sort_order', 'title']},
        ),
        migrations.AlterModelOptions(
            name='sweetspotstrength',
            options={'ordering': ['sort_order', 'title']},
        ),
        migrations.AlterModelOptions(
            name='sweetspotvalue',
            options={'ordering': ['sort_order', 'title']},
        ),
        migrations.AlterField(
            model_name='sweetspot',
            name='impactother',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='sweetspot',
            name='strengthother',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='sweetspot',
            name='valueother',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
