# Generated by Django 3.2.9 on 2022-01-07 09:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Timeentry',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now=True)),
                ('annual_leave', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Annual leave')),
                ('statutory_holiday', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Statutory holiday')),
                ('sick_leave', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Sick leave')),
                ('hr_recruitment', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='HR Recruitment')),
                ('sustainability', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Sustainability')),
                ('design_architecture', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Design / architecture')),
                ('functional', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Functional')),
                ('admin_pmo', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Admin PMO Financial')),
                ('comms_marketing', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Comms / marketing')),
                ('product_development', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Product development (tech)')),
                ('user_research', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='User research')),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
