# Generated by Django 3.2.9 on 2022-01-07 14:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whyness_timesheet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeentry',
            name='admin_pmo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='Admin PMO Financial'),
        ),
        migrations.AlterField(
            model_name='timeentry',
            name='annual_leave',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='Annual leave'),
        ),
        migrations.AlterField(
            model_name='timeentry',
            name='comms_marketing',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='Comms / marketing'),
        ),
        migrations.AlterField(
            model_name='timeentry',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='timeentry',
            name='design_architecture',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='Design / architecture'),
        ),
        migrations.AlterField(
            model_name='timeentry',
            name='functional',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='Functional'),
        ),
        migrations.AlterField(
            model_name='timeentry',
            name='hr_recruitment',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='HR Recruitment'),
        ),
        migrations.AlterField(
            model_name='timeentry',
            name='product_development',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='Product development (tech)'),
        ),
        migrations.AlterField(
            model_name='timeentry',
            name='sick_leave',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='Sick leave'),
        ),
        migrations.AlterField(
            model_name='timeentry',
            name='statutory_holiday',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='Statutory holiday'),
        ),
        migrations.AlterField(
            model_name='timeentry',
            name='sustainability',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='Sustainability'),
        ),
        migrations.AlterField(
            model_name='timeentry',
            name='user_research',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='User research'),
        ),
    ]
