# Generated by Django 3.2.11 on 2022-02-14 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('whyness_django', '0022_tracker_trackeritem'),
    ]

    operations = [
        migrations.CreateModel(
            name='DreamJob',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ip', models.GenericIPAddressField(default='::1')),
                ('role1', models.CharField(default='', max_length=100)),
                ('role2', models.CharField(default='', max_length=100)),
                ('role3', models.CharField(default='', max_length=100)),
                ('profession1', models.CharField(default='', max_length=100)),
                ('profession2', models.CharField(default='', max_length=100)),
                ('profession3', models.CharField(default='', max_length=100)),
                ('company_size', models.CharField(default='', max_length=100)),
                ('office_culture', models.CharField(default='', max_length=100)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='whyness_django.authuser')),
                ('useragent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='whyness_django.useragent')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
