# Generated by Django 3.2.11 on 2022-02-14 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('whyness_django', '0022_tracker_trackeritem'),
        ('whyness_appgyver_polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SweetSpotImpact',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='', max_length=100)),
                ('status', models.SmallIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='SweetSpotStrength',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='', max_length=100)),
                ('status', models.SmallIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='SweetSpotValue',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='', max_length=100)),
                ('status', models.SmallIntegerField(default=1)),
            ],
        ),
        migrations.AddField(
            model_name='dreamjob',
            name='update_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='SweetSpot',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ip', models.GenericIPAddressField(default='::1')),
                ('valueother', models.CharField(default='', max_length=100)),
                ('strengthother', models.CharField(default='', max_length=100)),
                ('impactother', models.CharField(default='', max_length=100)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('impact1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='whyness_appgyver_polls.sweetspotimpact')),
                ('impact2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='whyness_appgyver_polls.sweetspotimpact')),
                ('impact3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='whyness_appgyver_polls.sweetspotimpact')),
                ('impact4', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='whyness_appgyver_polls.sweetspotimpact')),
                ('impact5', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='whyness_appgyver_polls.sweetspotimpact')),
                ('strength1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='whyness_appgyver_polls.sweetspotstrength')),
                ('strength2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='whyness_appgyver_polls.sweetspotstrength')),
                ('strength3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='whyness_appgyver_polls.sweetspotstrength')),
                ('strength4', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='whyness_appgyver_polls.sweetspotstrength')),
                ('strength5', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='whyness_appgyver_polls.sweetspotstrength')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='whyness_django.authuser')),
                ('useragent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='whyness_django.useragent')),
                ('value1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='whyness_appgyver_polls.sweetspotvalue')),
                ('value2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='whyness_appgyver_polls.sweetspotvalue')),
                ('value3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='whyness_appgyver_polls.sweetspotvalue')),
                ('value4', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='whyness_appgyver_polls.sweetspotvalue')),
                ('value5', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='whyness_appgyver_polls.sweetspotvalue')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
