# Generated by Django 3.2.11 on 2022-02-19 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whyness_appgyver_polls', '0004_usersql'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserSQL',
        ),
    ]
