# Generated by Django 3.2.12 on 2022-02-20 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whyness_appgyver_polls', '0005_delete_usersql'),
    ]

    operations = [
        migrations.AddField(
            model_name='dreamjob',
            name='professionconfidence',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='dreamjob',
            name='roleconfidence',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='sweetspot',
            name='impactconfidence',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='sweetspot',
            name='strengthconfidence',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='sweetspot',
            name='valueconfidence',
            field=models.CharField(default='', max_length=100),
        ),
    ]
