# Generated by Django 3.2.12 on 2022-02-21 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whyness_appgyver_polls', '0006_auto_20220220_1233'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sweetspot',
            name='impact4',
        ),
        migrations.RemoveField(
            model_name='sweetspot',
            name='impact5',
        ),
        migrations.RemoveField(
            model_name='sweetspot',
            name='strength4',
        ),
        migrations.RemoveField(
            model_name='sweetspot',
            name='strength5',
        ),
        migrations.RemoveField(
            model_name='sweetspot',
            name='value4',
        ),
        migrations.RemoveField(
            model_name='sweetspot',
            name='value5',
        ),
    ]
