# Generated by Django 3.2.12 on 2022-02-21 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whyness_appgyver_polls', '0007_auto_20220221_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sweetspot',
            name='impact1',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='sweetspot',
            name='impact2',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='sweetspot',
            name='impact3',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='sweetspot',
            name='strength1',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='sweetspot',
            name='strength2',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='sweetspot',
            name='strength3',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='sweetspot',
            name='value1',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='sweetspot',
            name='value2',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='sweetspot',
            name='value3',
            field=models.CharField(default='', max_length=100),
        ),
    ]
