# Generated by Django 3.2.15 on 2022-09-09 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('insert_id', models.CharField(default='', max_length=36)),
                ('event', models.CharField(default='', max_length=100)),
                ('user', models.CharField(default='', max_length=36)),
                ('ip', models.GenericIPAddressField(default='::1')),
                ('useragent', models.CharField(default='', max_length=500)),
                ('method', models.CharField(default='', max_length=20)),
                ('time', models.PositiveIntegerField()),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('status_code', models.PositiveSmallIntegerField(default=0, verbose_name='Status code')),
                ('message', models.TextField(default='')),
            ],
        ),
    ]
