# Generated by Django 3.2.16 on 2022-10-25 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('whyness_joblist', '0002_auto_20220904_1604'),
    ]

    sql_insert_industries = """
    INSERT INTO whyness_joblist_industry (name, update_ip, update_date, create_date)
    VALUES ('tba', '::1', now(), now());
    """

    operations = [
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('update_ip', models.GenericIPAddressField(default='::1')),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.RunSQL(
            sql=[
                sql_insert_industries,
            ],
            reverse_sql=[],
        ),
        migrations.AddField(
            model_name='job',
            name='industry',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='whyness_joblist.industry'),
            preserve_default=False,
        ),
    ]
