# Generated by Django 3.2.10 on 2022-01-11 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whyness_django', '0004_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='sort_order',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
