# Generated by Django 3.2.10 on 2022-01-12 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whyness_django', '0005_question_sort_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['sort_order']},
        ),
        migrations.AddField(
            model_name='audio',
            name='transcript',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='audio',
            name='transcript_s3',
            field=models.TextField(default=''),
        ),
    ]
