# Generated by Django 3.2.10 on 2022-01-12 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whyness_django', '0006_auto_20220112_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='transcript_s3',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
