# Generated by Django 3.2.10 on 2022-01-13 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whyness_django', '0007_alter_audio_transcript_s3'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='transcribe_job_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='audio',
            name='transcribe_status',
            field=models.CharField(default='', max_length=20),
        ),
    ]
