# Generated by Django 3.2.10 on 2022-01-13 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whyness_django', '0008_auto_20220113_1923'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='transcribe_status_json',
            field=models.CharField(default='', max_length=20),
        ),
    ]
