# Generated by Django 3.2.11 on 2022-02-02 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whyness_django', '0014_auto_20220126_1749'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='representational_system',
            field=models.TextField(default=''),
        ),
    ]
