# Generated by Django 3.2.11 on 2022-02-07 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whyness_django', '0015_audio_representational_system'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TypeAttributes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='audio',
            options={'ordering': ['-id'], 'verbose_name_plural': 'Audio'},
        ),
        migrations.AlterField(
            model_name='audio',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'Inactive'), (1, 'Active'), (2, 'Sent for transcription'), (3, 'Transcription in progress'), (4, 'Transcribed'), (5, 'Transcription failed'), (6, 'Representational system'), (8, 'Deleted')], default=1),
        ),
        migrations.CreateModel(
            name='RoleTypeAttributes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('attributes', models.ManyToManyField(to='whyness_django.TypeAttributes')),
            ],
        ),
    ]
