# Generated by Django 3.2.11 on 2022-02-07 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('whyness_django', '0016_auto_20220207_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='profession',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='whyness_django.profession'),
            preserve_default=False,
        ),
    ]
