# Generated by Django 3.2.11 on 2022-02-07 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whyness_django', '0017_role_profession'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='attributes',
            field=models.ManyToManyField(to='whyness_django.TypeAttributes'),
        ),
        migrations.DeleteModel(
            name='RoleTypeAttributes',
        ),
    ]
