# Generated by Django 3.2.11 on 2022-02-07 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whyness_django', '0018_auto_20220207_1525'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='typeattributes',
            options={'verbose_name_plural': 'Type attributes'},
        ),
        migrations.RenameField(
            model_name='audio',
            old_name='uid',
            new_name='user',
        ),
        migrations.AddField(
            model_name='authuser',
            name='name',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='authuser',
            name='email',
            field=models.CharField(default='', max_length=250),
        ),
    ]
