# Generated by Django 3.2.11 on 2022-02-10 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('whyness_django', '0021_typeattributes_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackerItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TrackerLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ip', models.GenericIPAddressField(default='::1')),
                ('method', models.CharField(default='', max_length=20)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='whyness_django.trackeritem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='whyness_django.authuser')),
                ('useragent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='whyness_django.useragent')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
