# Generated by Django 3.2.12 on 2022-03-07 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whyness_django', '0025_alter_audio_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'Inactive'), (1, 'Active'), (2, 'Sent for transcription'), (3, 'Transcription in progress'), (4, 'Transcribed'), (5, 'Transcription failed'), (6, 'Representational system'), (8, 'MBTI'), (98, 'Deleted')], default=1),
        ),
    ]
